-- SQL statements that are used to define the breadth-first search function
-- Include all your tried solutions in the SQL file
-- with commenting below the functions the execution times on the tested dictionaries.