-- SQL statements that are used to define the Levenshtein distance function
-- Include all your tried solutions in the SQL file
-- with commenting below the functions the execution times on the tested dictionaries.